version: '2'
services:
  bymi-app:
    image: bymi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bymi-postgresql:5432/Bymi
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bymi-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bymi-elasticsearch:9200
    ports:
      - 8080:8080
  bymi-postgresql:
    extends:
      file: postgresql.yml
      service: bymi-postgresql
  bymi-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bymi-elasticsearch
